# Generated by Django 4.1 on 2022-09-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_is_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_done',
            new_name='is_finished',
        ),
    ]
